name: fast_location
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_foundation: ^2.0.9
  map_launcher: ^3.3.0
  geocoding: ^3.0.0
  get_it: ^7.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

build_runner:
  options:
    output: lib/src/generated